particles: [Lambda, Lambdabar]
flows: [v1]
energies: [7p7GeV, 9p2GeV, 11p5GeV, 14p6GeV, 17p3GeV, 19p6GeV, 27GeV]
yrebin: 
  7p7GeV:  {Lambda: 1, Lambdabar: 1, Xi: 4, Xibar: 4}
  9p2GeV:  {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
  11p5GeV: {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
  14p6GeV: {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
  17p3GeV: {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
  19p6GeV: {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
  27GeV:   {Lambda: 1, Lambdabar: 1, Xi: 2, Xibar: 2}
merged_xi_cen_bins:
  27GeV: [[1,2],[3],[4],[5],[6],[7],[8],[9]]
  19p6GeV: [[1,2],[3],[4],[5],[6],[7],[8],[9]]
  17p3GeV: [[1,2],[3],[4],[5],[6],[7],[8],[9]]
  14p6GeV: [[1,2],[3],[4],[5],[6],[7],[8],[9]]
  11p5GeV: [[1,2],[3],[4],[5],[6],[7],[8],[9]]
  9p2GeV: [[1,2,3],[4],[5],[6],[7],[8],[9]]
  7p7GeV: [[1,2,3,4],[5,6,7],[8,9]]
fit_order: {7p7GeV: 1, 9p2GeV: 1, 11p5GeV: 1, 14p6GeV: 1, 17p3GeV: 1, 19p6GeV: 1, 27GeV: 1}
pt_lo: 0.4
pt_hi: 1.8
y_cut: 0.6
# for piKp pt
piKp_ptnq_lo: 0.14
piKp_ptnq_hi: 0.6
nquark: 
  pions: 2
  protons: 3
  kaons: 2
plotting:
  7p7GeV: {v2_lo: -0.2, v2_hi: 0.15}
  9p2GeV: {v2_lo: -0.2, v2_hi: 0.15}
  11p5GeV: {v2_lo: -0.2, v2_hi: 0.15}
  14p6GeV: {v2_lo: -0.1, v2_hi: 0.05}
  17p3GeV: {v2_lo: -0.1, v2_hi: 0.05}
  19p6GeV: {v2_lo: -0.1, v2_hi: 0.05}
  27GeV: {v2_lo: -0.1, v2_hi: 0.05}
  



